### ISSUE TITLE
does anybody have success on talking with Wanderer 10A

### ISSUE THREAD

**Issue by lzhengchun** [BarkinSpider/SolarShed#7]
I have iterated all address from 0 to 255, to read register 0x103(also tried other register), always no response.

I was wondering if I made anything wrong, or WND10 does not support modbus? 
or does anyone have success on using bluetooth module with WND10?

**Comment by spurgelaurels** [comment]
I was able to get mine to work on Channel 255 with the correct wiring.

**Comment by lzhengchun** [comment]
I also made it work, it is pretty picky on usb-to-RS232 adapter, I tried a few and finally find a quality one that worked.
yes, address is 255, i have this config

`
self.devfd = minimalmodbus.Instrument('/dev/ttyUSB0', 255)

self.devfd.serial.baudrate = 9600

self.devfd.serial.bytesize = 8

self.devfd.serial.parity   = serial.PARITY_NONE

self.devfd.serial.stopbits = 1

self.devfd.serial.timeout  = .5

self.devfd.debug = False
`
